name: machine-learning-book
channels:
  - conda-forge
  - defaults
  - pytorch
  - nvidia
  - pip
dependencies:
  - numpy=1.21.2
  - pandas=1.3.2
  - python=3.9
  - matplotlib=3.4.3
  - scikit-learn=1.0
  - jupyterlab>=3.4.4
  - ipykernel
  - jupyterlab
  - nltk=3.6
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - conda-forge::scipy=1.7.0
  - conda-forge::pytorch-lightning
  - conda-forge::tensorboard
  - pip::XGBoost==1.5.0
  - pip::pyprind==2.11.3
  - pip::mlxtend==0.19.0

